### ISSUE TITLE
Mark functions as private or public in the api.

### ISSUE THREAD

**Issue by olach** [wpseek/wpseek-web#1]
Would be great if the api marked functions as public or private.

**Comment by oliverschloebe** [comment]
By functions you mean class methods? Or internal functions?

**Comment by olach** [comment]
I mean that all functions that mostly apply to the core WordPress code should be marked as private (or internal). Functions that not should be used in a custom plugin or a theme.

The rest of the functions that normally will be used in plugins or themes could be marked as public.

**Comment by oliverschloebe** [comment]
Added: http://wpseek.com/_add_post_type_submenus/?nocache

Will be staging to Live soon.

**Comment by olach** [comment]
Are you going to implement this to your api as well?

No information here yet:
http://api.wpseek.com/?method=wordpress.getfunction&s=_add_post_type_submenus

**Comment by oliverschloebe** [comment]
Added. It's up to the dev how to use the 'access' or 'deprecated' info in their web app to display alerts or whatever.

**Comment by olach** [comment]
Thanks!
