### ISSUE TITLE
Plugin Doctor result is letter instead of number

### ISSUE THREAD

**Issue by joyously** [wpseek/wpseek-web#14]
I loaded a theme zip file to Plugin Doctor desktop version and it gave me the result:
Requires at least: M

It listed one deprecated function, and all the functions on the right, but I have to go look at each one to find the version information.
The M could be from one file which listed:
get_post_format  3
get_template_part 3
have_posts 1
is_sticky 2
the_post  1
Unknown version information
Missing version information

**Comment by joyously** [comment]
I narrowed it down. The function get_current_user_id has a version number of MU, so that messes up everything after it.
Also, function add_theme_page says N/A.

**Comment by oliverschloebe** [comment]
Hi joyously!

The issue was caused by #13 and has been fixed.

Thanks!

**Comment by joyously** [comment]
The fix for #13 certainly helped! I now get a number for the same zip file, and each function is showing a version number instead of an integer.

However, the end result number is not necessarily correct because the version number of MU still affects what comes after it. See attached screenshot and note the functions after the MU don't have a number.
![capture619-plugin doctor - wpseek_bug](https://cloud.githubusercontent.com/assets/7957680/3942015/6f3fc1bc-254f-11e4-8aea-ea168c42ecd5.jpg)

**Comment by oliverschloebe** [comment]
Hey joyously, that's intentional. See the subheadings. :) Some functions don't have version information in their doc blocks, so I'm listing them under separate subheadings to clearify that version info are missing.

![Image](http://screens.schloebe.de/image_2014-08-16_16_21_21_000.jpg)

**Comment by joyously** [comment]
Wow, you should change how you present the information. I had no idea those were headings. They looked like warning messages you output as you went. Maybe it's because the first section doesn't have a header of that same size and also because you put out the header even if there's nothing under it.
Maybe the Missing and Unknown should go on the left with the Deprecated.

**Comment by oliverschloebe** [comment]
You have probably guessed that I'm not a designer by now. :D But you're right. The headings might get lost there.

**Comment by oliverschloebe** [comment]
Changed the layout of the "Function Breakdown" a little which should make the headings more obvious.

**Comment by joyously** [comment]
Looks much better.
