### ISSUE TITLE
Plugin Doctor broken

### ISSUE THREAD

**Issue by JDGrimes** [wpseek/wpseek-web#16]
I just tried using the plugin doctor, but it never comes up with the result. The reason is that it is getting this in the response:

```
<br />
<b>Notice</b>:  Undefined offset: 0 in <b>/var/www/vhosts/wpseek.com/httpdocs/content.php</b> on line <b>323</b><br />
<br />
<b>Notice</b>:  Undefined offset: 0 in <b>/var/www/vhosts/wpseek.com/httpdocs/content.php</b> on line <b>324</b><br />
```

So it can't parse the response, since that makes it invalid. If you need a copy of the .zip I am using, let me know.

**Comment by oliverschloebe** [comment]
Fixed. I suppose you've had a folder named `__MACOSX` in the ZIP file, which includes Mac-style line feeds that screwed my parser. Made a few changes to avoid those kind of things in the future.

Thanks! :)
