### ISSUE TITLE
WordPress "compat functions"

### ISSUE THREAD

**Issue by tillkruss** [wpseek/wpseek-web#18]
Some of the WordPress "compat functions" are available: 
- http://api.wpseek.com/?method=wordpress.getfunction&s=hash_equals

But some of them aren't:
- http://api.wpseek.com/?method=wordpress.getfunction&s=json_decode

And some are incomplete:
- http://api.wpseek.com/?method=wordpress.getfunction&s=hash_hmac

I'd recommend removing all WordPress compatibility functions from the API.

**Comment by oliverschloebe** [comment]
Well, I'm not sure if completely removing all WordPress compatibility functions from wpseek.com is the right decision. E.g. `hash_equals` was added in PHP 5.6, but WordPress' PHP requirement is 5.2.5 so plugins and themes might still need/use this and other WordPress compatibility functions.

**Comment by tillkruss** [comment]
I agree that `hash_equals()` should stay, but `hash_hmac()` could be removed entirely, since it's incomplete, anyhow.

**Comment by oliverschloebe** [comment]
I agree. `hash_hmac()` will be removed after the next update cycle on wpseek.com.
