### ISSUE TITLE
Possible Listing Directory Vulnerability

### ISSUE THREAD

**Issue by mikel-hernandez1** [wpseek/wpseek-web#35]
Hola buenas! He encontrado un posible directorio que no estoy seguro si debería ser accesible. ¿Podrían revisarlo? (No quiero hacerlo público por aquí)

**Comment by oliverschloebe** [comment]
> Hola buenas! He encontrado un posible directorio que no estoy seguro si debería ser accesible. ¿Podrían revisarlo? (No quiero hacerlo público por aquí)

Hi, please send it to office (at) wpseek (dot) com

Thank you!
